python3 panda_vanilla.py \
    --dataset cifar10 \
    --label 0 \
    --epochs 30 \
    --resnet_type 18 \
    --output_dir train_results \
    --seed 42 \
    --severity 1 \
    --interval 5 \
    --data_root ~/data\
    --ewc 